### ISSUE TITLE
json data storage

### ISSUE THREAD

**Issue by CSomerville** [CSomerville/blind_ardor#1]
Hey Jeff,

I'm working on seeding the db right now (see trello link below). Conceptual question: I originally thought not to put the (rather large) JSON files I am using to seed the psql db inside the repo. I then considered that they would need to be there for deployment. Any thoughts as to which way I should go?

https://trello.com/c/jHlNwKcS/5-a-designer-can-see-a-map-of-nyc-and-can-layer-trees-on-top-so-that-they-can-decide-which-trees-should-be-on-the-path

**Comment by jkonowitch** [comment]
How big is the file?

**Comment by CSomerville** [comment]
approx 300 mb
