### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by CSomerville** [CSomerville/blind_ardor#2]
Hey Jeff,

Hope your weekend was nice. A little over my head with DO deployment. I installed rails, and the server seems to start fine with a test app. However, when I navigate to the ip address from my machine I don't get the friendly welcome to rails page.

Also, I installed postgres, but got stuck at the point where I needed to set up a user--a little fuzzy on the concept of users on a remote machine.

Thanks for all you help!

**Comment by jkonowitch** [comment]
Thanks Colby. 

OK - we should chat about this briefly. I'll slack you after I'm done with Nesta.

**Comment by CSomerville** [comment]
Oh man -- I think my droplet can't handle my seed file. Jun  8 16:09:41 boldFish kernel: [6046138.188617] Out of memory: Kill process 2308 (rake) score 774 or sacrifice child
Jun  8 16:09:41 boldFish kernel: [6046138.188742] Killed process 2308 (rake) total-vm:584712kB, anon-rss:399760kB, file-rss:0kB

**Comment by CSomerville** [comment]
Maybe get a bigger one?

**Comment by jkonowitch** [comment]
You could get a box with bigger memory. You could also read the file line by line instead of all at once. That would cut down on memory usage.

**Comment by CSomerville** [comment]
Oh thanks so much for responding! Will try the line by line option first.

‏في الاثنين، ٨ يونيو، ٢٠١٥, Jeffrey Konowitch notifications@github.com
كتب:

> You could get a box with bigger memory. You could also read the file line
> by line instead of all at once. That would cut down on memory usage.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CSomerville/blind_ardor/issues/2#issuecomment-110176324
> .

##
